### ISSUE TITLE
Update: Adding Semgrep Rules

### ISSUE THREAD

**Issue by salecharohit** [OWASP/CheatSheetSeries#457]
## What is missing or needs to be updated?
Cheatsheet series contain plenty of code snippets which either highlight good practice or a sample vulnerable code. For Ex: This [XXE code snippet](https://cheatsheetseries.owasp.org/cheatsheets/XML_External_Entity_Prevention_Cheat_Sheet.html#jaxp-documentbuilderfactory-saxparserfactory-and-dom4j) very well highlights the idea of using the setFeature function whenever instantiating a DocumentBuilderFactory class.
At times developers can miss out on these best practices due to many reasons
Is there any way in which we can enforce these best practices or help them identify vulnerable code snippets by making using of a lightweight utility that allows them to write their own rules?

## How should this be resolved?
[Semgrep](https://semgrep.live/) is an opensource tool for scanning source code supporting various languages like Java,Python,Javascript,Go,C etc ... The beauty of Semgrep is that allows the developers to write their own rules where they can enforce the security best practices or identify vulnerable code snippets. Its fast,sleek and easy to use.
As an example , for the above XXE DocumentBuilderFactory code the below Semgrep rule can easily identify whether a DocumentBuilderFactory has been instantiated WITHOUT calling the setFeature function.

```yaml
rules:
- id: XXE
  message: |
    Generic XXE
  metadata:
    owasp: "A4: XXE"
  severity: ERROR
  patterns:
  - pattern-either: 
    - pattern: DocumentBuilderFactory $DBF = $W.newInstance();
  - pattern-not-inside: |
      $RETURNTYPE $METHOD(...) {
        ...
        $DBF.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        ...
      }     
  languages:
  - java
```
You can also try this rule live here [https://semgrep.live/salecharohit:xxe](https://semgrep.live/salecharohit:xxe)

What i wish to propose is to inject Semgrep rules in the Cheatsheet series where developers can simply copy/clone/fork the rules provided at the particular topic and reuse them.
For Ex: at the same XXE cheatsheet while discussing on best practices for DocumentBuilderFactory I can add a Semgrep rule or a URL of the semgrep.live editor or maybe both which the reader can then reuse in his/her code base or Semgrep rules.
Please Note : Every Cheatsheet may require multiple updates.
